#define CPU_ANALYSER_FREQUENCY FREQUENCY_10Hz
#define SERIAL_OBSERVER_PERIOD FREQUENCY_20Hz

#define EV_INTEGRATE_FREQUENCY              FREQUENCY_50Hz
#define EV_CALCULATE_ANGLES_FREQUENCY       FREQUENCY_50Hz
#define EV_MAGNETOMETERS_FREQUENCY          FREQUENCY_50Hz
#define EV_UPDATE_LED_POSITION_FREQUENCY    FREQUENCY_20Hz
#define EV_DISPLAY_DATA_FREQUENCY           FREQUENCY_20Hz

#define EV_STABILISATION_FREQ               FREQUENCY_20Hz
